### PR TITLE
Add tx_hash to returning tuple at contract's deployment

### PR DESCRIPTION
**Pull request by pik694**

### CODE REVIEW

**Comment by hswick** [comment]
Looks like there is just a small conflict and I'll be happy to merge it as well.

**Comment by pik694** [comment]
Indeed, it is caused by the fact that those changes are totally different from the one form #11 and I preferred to create other PR, but unfortunately I had to change the same code twice. In my forked repo there is a branch with resolved conflicts, if you want I can merge this branch with the one with resolved conflicts so you will be allowed to merge this PR smoothly.
Check this one: User/Repository@SHA: omisego/exw3@8d3701478bb64bd142fc5f902f1b45dba3f41ef1

**Comment by hswick** [comment]
That would be great!

**Comment by pik694** [comment]
It is ready to be merged :)

**Pull request merged**
