### PR TITLE
Adding support for struct decoding - fix encoding bug

### PR DESCRIPTION
**Pull request by gregors**
Hello. You ever have one of those days where you are just click-clacking around having a good old time, when BAM - you get

```elixir
[error] GenServer ContractManager terminating
** (FunctionClauseError) no function clause matching in ABI.TypeDecoder.decode_type/2
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:245: ABI.TypeDecoder.decode_type(:tuple, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 141, 21, 225, 118, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>)
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:271: anonymous fn/3 in ABI.TypeDecoder
```

 Ouch!

You take a look at the stack trace and cruise on over to `ex_abi` and look for similar issues and find https://github.com/poanetwork/ex_abi/issues/51. Hmmmm the journey begins.

The following is a brief tale of sorrow and glory. I was attempting to retrieve a Struct from a smart contract, but when making the call boom - error. Surely I did something wrong. I double check things and start to presume that I didn't do anything incorrectly (a fairly dangerous assumption to be sure). After looking for awhile I notice the following code:
```elixir
    output_types = Enum.map(abi[name]["outputs"], fn x -> x["type"] end)
    types_signature = Enum.join(["(", Enum.join(output_types, ","), ")"])
    output_signature = "#{name}(#{types_signature})"
```

which for a struct returns the following type
```elixir
"get((tuple[]))"
```

If you follow the trail into `ABI.decode` you'll find that that string representation makes it way through `Parser.parse!()`
resulting in the following function selector type
```elixir
types: [tuple: [array: :tuple]]
```

that last `:tuple` is what makes `ex_ab` blow up. Hmmm but why?????
It turns out that defined in the latest https://docs.soliditylang.org/en/v0.8.10/abi-spec.html structs are handled as tuples - and are handled differently

> Handling tuple types
> Despite that names are intentionally not part of the ABI encoding they do make a lot of sense to be included
> in the JSON to enable displaying it to the end user. The structure is nested in the following way:
>
> An object with members name, type and potentially components describes a typed variable. The canonical type
> is determined until a tuple type is reached and the string description up to that point is stored in type
> prefix with the word tuple, i.e. it will be tuple followed by a sequence of [] and [k] with integers k.
> ***The components of the tuple are then stored in the member components***, which is of array type and has the
> same structure as the top-level object except that indexed is not allowed there.

So the code above fails to work for decoding struct. The type is incorrect and `ex_ab` chokes on the bad input. It's expecting something like the following instead:
```elixir
[array: {:tuple, [uint: 256, uint: 256]}]
```

Well....hmmm, that code doesn't currently do that? We'll need to checkout the `components` section of the abi - write unit tests and write some logic???
It turns out ABI has done all that right over here >>>> https://github.com/poanetwork/ex_abi/blob/master/test/abi/type_decoder_test.exs#L137

So there isn't a need for us to reinvent the wheel.
I started off with creating a failing test - added a new smart contract that shows off how a returning struct fails. Great. Now we'll just change a bit of code to parse the abi passed in using the `elixir ABI.parse_specification ` function that parses the abi and does all the heavy lifting of figuring out how to deal with weird tuple types. Great!

My test passes!!! Woo Hoo! Ready to submit a PR.....and whoa hold my horses. When I run a full test I now get a failing test for an seemingly unrelated issue.

That night instead of sleeping I spend that night thinking about what I did that would break other things?

Day 2

 I dig into the failing ArrayTester test and I notice the following.

` {:ok, result} = ExW3.Contract.call(:ArrayTester, :dynamicUint, [1, 2, 3])`

which uses

`ABI.TypeEncoder.encode_raw`

under the hood.

The encoding that is sent is as follows:
```
0x5d4e0342
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000003
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000003
```

The expected return value is `[1,2,3]` however, we send something extra. Upon receipt of the call we get the result of what was sent
```
[3,1,2,3,0,0,0.......
```
That's *definitely* not right!

Running the same contract in Remix I see the following encoding:
```
0x5d4e0342
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000003
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000003
```
Which omits the extra empty segments and does result in the expected results of `[1,2,3]`

I'm curious if that extra encoding existed prior to my pesky meddling? And it does. The encoding has always been off. It turns out that my *fix* of using the correct type started to correctly decode - wrong encoded things - ending up with a single failing test. wow.

That's right, we're unnecessarily wrapping everything in an extra tuple. If you compare what `exw2` encodes to other libraries - there's always an extra tuple. Hmmmm.

OK no big deal, just remove the extra tuple. However, when you do that you get all kinds of errors.

If I compare the types `ex_abi` is working with we see the following
```elixir
ABI.FunctionSelector.decode_raw("(uint256[])")
{:tuple, [array: {:uint, 256}]}
```

vs

```elixir
iex(2)> ABI.FunctionSelector.decode_raw("uint256[]")
[uint: 256]
```

Let's look at that again:

```elixir
iex(1)> ABI.FunctionSelector.decode_raw("(uint256[])")
[tuple: [array: {:uint, 256}]]
iex(2)> ABI.FunctionSelector.decode_raw("uint256[]")
[array: {:uint, 256}]
```

Notice those extra parentheses? Now, check this very very similar method out:
```elixir
iex(2)> ABI.FunctionSelector.decode("(uint256[])")
%ABI.FunctionSelector{
  function: nil,
  input_names: [],
  inputs_indexed: nil,
  method_id: nil,
  returns: [],
  type: nil,
  types: [array: {:uint, 256}]
}
iex(3)> ABI.FunctionSelector.decode("uint256[]")
** (MatchError) no match of right hand side value: {:error, {1, :ethereum_abi_parser, ['syntax error before: ', '\'[\'']}}
    (ex_abi 0.5.7) lib/abi/parser.ex:15: ABI.Parser.parse!/2
```

It turns out that `decode_raw` adds extra parans .....because the ABI.Parser syntax needs it - it's part of that AST, It's not a tuple at all!
`decode` assumes you've added that those extra parans. `_raw` functions don't.

```elixir
def decode_raw(type_string) do
  {:tuple, types} = decode_type("(#{type_string})")
  types
end
```

And my code is using both versions so I fix the array test and it causes other tests to break. So I fixed those as well. I also noticed that the commented out tests don't actually pass in ganache at all the return types where incorrect you can't add `{:ok, 5} + 5` so I also fixed those. So recap.

* added a test to highlight returning a struct
* added code to make structs pass
* added code to remove the extra tuple we were mistakenly wrapping all the types in (or at least that's what it looked like to me)
* got the commented out tests passing again

Some other thoughts - I'm currently parsing the abi file for every call. It would be much much better to parse that as part o the abi loading, but I think this had enough churn without adding that. I appreciate and look forward to your feedback as well as any clarifications you could make since I probably misunderstood something along the way. Notice I haven't written a test for *passing* a struct into a call. I think even if you don't like or use the implementation the test will highlight the goal of why I started down this path in the beginning. Thanks!

### CODE REVIEW

**Comment by gregors** [comment]
rebased on master

**Comment by gregors** [comment]
@rupurt

**Comment by gregors** [comment]
I do get all passing on my fork

**Comment by rupurt** [comment]
@gregors thanks for updating. Sorry for the delayed response. I haven't had the time to dedicate to maintenance but starting to get back in the swing of things.

**Comment by hswick** [comment]
@gregors Thanks for this update! It seems that ex_abi has been updated and now exw3 doesnt need to try compensate for its behavior.

The extra parens were me wrapping ex_abi's output to something that was actually usable. Glad this got fixed upstream. It has been a while since I wrote that code and I haven't needed to change it.

As for the names for the structs #101 is generating contract code at compile time, so including the struct names might be a natural fit with that feature.

**Comment by gregors** [comment]
Gotcha - closing my PR since you seem to have a way forward. I would say that you may want to add tests that specifically test your encoding logic. I think most people would be surprised in a bad way to find incorrect encoding taking place under the hood.

**Comment by hswick** [comment]
Ah, I was a bit surprised you closed the PR. Your work seems quite helpful, I was merely suggesting that adding names for struct fields could be added after the contract compilation feature is added.

Your struct decoding I think is great and a welcome addition.

**Comment by gregors** [comment]
@hswick oh gotcha, I misunderstood. I'll re-open it. and see if I can incorporate the names.

**Comment by gregors** [comment]
actually I'll, refactor a bit to separate the encoding issues from the struct logic

**Pull request closed without merging**
