### PR TITLE
[Bugfix] ABI single string ouputs

### PR DESCRIPTION
**Pull request by willjleong**
**Notes**
- Kinda a very singular-purpose fix for single `:string` type outputs (which are pretty common with erc721 contracts. All tests pass & other logic still works.

**Changelog**
- [x] Setup Hardhat
- [x] Get Tests running locally
- [x] Replace old solc with hardhat
- [x] Create load_hardhat_abi to abi functions
- [x] Add logic to decode output of single outputs of ":string" type
- [x]  Bump `ex_abi` version to `0.5.5`

### CODE REVIEW

**Comment by hswick** [comment]
@willjleong Do you mind explaining why you decided to start a separate fork of exw3?

https://github.com/Metalink-App/ex_w3
I would have commented there, but it seems issues are disabled. 

Your changes aren't too controversial, and I think can easily be merged into this project. This PR was only open for a few days.

If you do decide to go along with your own fork, do you mind rebranding to something that doesn't look like the name of exw3 at all? Frankly, ex_w3 is not different enough and could be confusing to users of both this project and yours.

**Comment by willjleong** [comment]
@hswick I really needed the changes deployed asap for a feature build and couldn't wait for the maintainers to review and approve the PR. I didn't know how active `exw3` project was after finding it un-usable for :string type outputs for calls and saw the last non-dependabot PR was before June.

My apologies, I can change the `ex_web3` package to something else & use a different logo no problem, will do that today (I was in a rush to implement a few features)! I do plan to maintain a fork of your library for the sake of being able to keep improving and modifying the client easily when needed (feel free to take any of my modifications and add them back into exw3 as well). Thank you got making this library, it is very helpful :)

**Comment by hswick** [comment]
@willjleong I completely understand needing to get things done, and I'm very glad that exw3 can you help you do that. Personally, I would've accomplished this by using a git repo dependency in the mix config. That way you can get your feature push done without needing a whole separate project. I would prefer if we could find a way to not make a hard fork, as I don't think our goals are mutually exclusive.

As for the status of the project, you are right, it is not actively developed on at the moment. However, @rupurt has been doing a great job of keeping up with the maintenance. I would encourage you to make PRs for the features you want, and I believe he would get those merged in a timely manner. If you stick with exw3, the long term maintenance burden can be shared. You might be inspired to work on this now, but how about in a few years from now?

I don't mean to be too defensive about the naming of the project. exw3 has been around for a while, and is typically pointed to as a beginner friendly solution to interact with ethereum via elixir. I would hate for newcomers to have the added complication of trying to figure if they should use exw3 or ex_w3. I will likely be okay with whatever best prevents that from happening.

Thanks for being understanding!

**Comment by willjleong** [comment]
@hswick I've gone ahead and renamed our repo to `web3x` do there's no confusion with `exw3`. I will delete `ex_w3` from hex tomorrow. If I wasn't working on a project with critical features dependent on our fork, I'd would have gladly helped maintain & develop this project. I've been studying `blockscout` as well to eventually add a ws transport that could be used to communicate with infura or alchemy ws uris to optimize interaction with the ethereum in the modern way.

I totally understand your concern with the project naming and apologize if it may have offended you - Under the pressure to deliver a feature for a project I went strait to publishing the fork to hex rather than using a git repo dependency in the project's internal project's mix config.

On a side note, I'm quite sad there aren't really any actively maintained elixir ethereum libraries updated to work with the cutting edge of the web3 / ethers ecosystem (in the JS/TS world) except maybe blockscout, which is overly complicated for most use cases and not really split up into reusable packages. OTP is a great tool for syncing/caching state from the blockchain and/or listening for smart-contract events.

Once again, thanks again for all your hard work, this library is very awesome 👍 .

**Comment by rupurt** [comment]
@willjleong I totally echo the sentiments of @hswick. Happy to help out on PR's where needed.

**Pull request closed without merging**
